services:
  - type: web
    name: telegram-bot
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        sync: false
